name: text_field_widget
description: Makes an interesting Text Field Widget
version: 0.0.2
homepage: https://github.com/j-j-gajjar
repository: https://github.com/j-j-gajjar/TextFIeldWidget

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
